AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  
Globals:
  Function:
    Timeout: 600

Resources:

  ExpressApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      BinaryMediaTypes: ['*/*']
  
  ExpressFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: server/
      Handler: lambda.handler
      Runtime: nodejs18.x
      MemorySize: 512
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
      Events:
        ExpressFunctionProxy:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: "/{proxy+}"
            Method: ANY
  
  ExpressEventBridge: 
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/
      Handler: eventBridge.handler
      Runtime: nodejs18.x
      MemorySize: 512
      
  ExpressEventRule: 
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      Description: "Event rules for Express function"
      ScheduleExpression: cron(0 14 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt ExpressEventBridge.Arn
          Id: ExpressFunctionTarget

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ecofrenzy-img
      AccessControl: BucketOwnerFullControl
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:PutObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${S3Bucket}/*
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ExpressEventBridge.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ExpressEventRule.Arn
      
Outputs:

  ExpressFunctiondApi:
    Description: "API Gateway endpoint URL for Prod stage for Express function"
    Value: !Sub "https://${ExpressApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  ExpressFunction:
    Description: "Express Lambda Function ARN"
    Value: !GetAtt ExpressFunction.Arn
  ExpressEventBridge:
    Description: "Express EventBridge Lambda Function ARN"
    Value: !GetAtt ExpressEventBridge.Arn
  ExpressEventRule:
    Description: "Express EventBridge Rule ARN"
    Value: !Ref ExpressEventRule
  S3BucketOutput:
    Description: "S3 Bucket for storing files"
    Value: !Ref S3Bucket
  # ExpressFunctionS3Policy:
  #   Description: "ExpressFunctionS3Policy"
  #   Value: !Ref ExpressFunctionS3Policy