AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  
Globals:
  Function:
    Timeout: 600

Resources:
  ExpressApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      BinaryMediaTypes: ['*/*']
      
  ExpressFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: server/
      Handler: lambda.handler
      Runtime: nodejs14.x
      MemorySize: 512
      Events:
        ExpressFunctionProxy:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: "/{proxy+}"
            Method: ANY
        ExpressFunctionRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: "/api"
            Method: ANY
  
  # ExpressEventBridge: 
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: server/
  #     Handler: eventBridge.handler
  #     Runtime: nodejs14.x
  #     MemorySize: 512
  #     Events:
  #       ExpressFunctionProxy:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref ExpressApi
  #           Path: "/"
  #           Method: ANY
  #       ExpressFunctionRoot:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref ExpressApi
  #           Path: "/eventBridge"
  #           Method: ANY

  # ExpressEventRule: 
  #   Type: AWS::Events::Rule
  #   Properties:
  #     EventBusName: default
  #     Description: "Event rules for Express function"
  #     ScheduleExpression: cron(10 9 * * ? *)
  #     State: ENABLED
  #     Targets:
  #       - Arn: !GetAtt ExpressEventBridge.Arn
  #         Id: ExpressFunctionTarget
      
Outputs:

  ExpressFunctiondApi:
    Description: "API Gateway endpoint URL for Prod stage for Express function"
    Value: !Sub "https://${ExpressApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  ExpressFunction:
    Description: "Express Lambda Function ARN"
    Value: !GetAtt ExpressFunction.Arn
  # ExpressEventBridge:
  #   Description: "Express EventBridge Lambda Function ARN"
  #   Value: !GetAtt ExpressEventBridge.Arn
  # ExpressEventRule:
  #   Description: "Express EventBridge Rule ARN"
  #   Value: !Ref ExpressEventRule