AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  S3 Bucket for storing files for EcoFrenzy

Resources:
  UploadImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ecofrenzy-upload-img
      AccessControl: BucketOwnerFullControl
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

Outputs:
  UploadImageBucket:
    Description: "S3 Bucket for storing files"
    Value: !Ref UploadImageBucket
