AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  S3 Bucket for storing files for EcoFrenzy

Resources:
  UploadImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ecofrenzy-upload-img
      AccessControl: BucketOwnerFullControl
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  ImageChallengeNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ImageChallengeNotificationTopic

  SNSCompleteChallengeTopic: 
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SNSCompleteChallengeTopic

Outputs:
  UploadImageBucket:
    Description: "S3 Bucket for storing files"
    Value: !Ref UploadImageBucket

  ImageChallengeNotificationTopic:
    Description: "Arn of SNS Topic for uploaded image & corresponding challenge notifications"
    Value: !Ref ImageChallengeNotificationTopic

  SNSCompleteChallengeTopic:
    Description: "Arn of SNS Topic for complete challenge notifications"
    Value: !Ref SNSCompleteChallengeTopic