// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWMzZIxu-Di_LspN_VOSR_vB0XKDab91E',
    appId: '1:677063964559:web:79e90d660af45b5b837dfa',
    messagingSenderId: '677063964559',
    projectId: 'ecofrenzy-ae321',
    authDomain: 'ecofrenzy-ae321.firebaseapp.com',
    storageBucket: 'ecofrenzy-ae321.appspot.com',
    measurementId: 'G-XK4PH7DS3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhmmc8u5DZqv-mbgnTLiXvQ29BQtv9ngA',
    appId: '1:677063964559:android:fb63d5032d2e6779837dfa',
    messagingSenderId: '677063964559',
    projectId: 'ecofrenzy-ae321',
    storageBucket: 'ecofrenzy-ae321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeVl5Nxo-vXJdBk2M0E6Mzgnp_gssUaNY',
    appId: '1:677063964559:ios:11d12e3d2d93ef59837dfa',
    messagingSenderId: '677063964559',
    projectId: 'ecofrenzy-ae321',
    storageBucket: 'ecofrenzy-ae321.appspot.com',
    iosClientId: '677063964559-g5skd2qntoqla8eoa0dls07n408v6ibt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeVl5Nxo-vXJdBk2M0E6Mzgnp_gssUaNY',
    appId: '1:677063964559:ios:65fbc0a3287f8669837dfa',
    messagingSenderId: '677063964559',
    projectId: 'ecofrenzy-ae321',
    storageBucket: 'ecofrenzy-ae321.appspot.com',
    iosClientId: '677063964559-snk2cvs87287a2vuk1diti8ac46pbi3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
