AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Express API Gateway and Lambda Function, with EventBridge

Parameters:
  UploadImageBucket:
    Type: String
    Description: "S3 Bucket for storing files"

  ImageChallengeNotificationTopic:
    Type: String
    Description: "Arn of SNS Topic for uploaded image & corresponding challenge notifications"

Resources:
  ExpressApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      BinaryMediaTypes: ["*/*"]

  ExpressFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ExpressFunctionServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ExpressFunctionS3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub arn:aws:s3:::${UploadImageBucket}/*

        - PolicyName: ExpressFunctionSNSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref ImageChallengeNotificationTopic

  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../server/
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 512
      Role: !GetAtt ExpressFunctionRole.Arn
      Events:
        ExpressFunctionProxy:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: "/{proxy+}"
            Method: ANY
      Environment:
        Variables:
          UPLOAD_IMAGE_BUCKET: !Ref UploadImageBucket
          IMAGE_CHALLENGE_NOTIFICATION_TOPIC: !Ref ImageChallengeNotificationTopic

  ExpressEventBridge:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../server/
      Handler: eventBridge.handler
      Runtime: nodejs14.x
      MemorySize: 512

  ExpressEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      Description: "Event rules for Express function"
      ScheduleExpression: cron(0 14 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt ExpressEventBridge.Arn
          Id: ExpressFunctionTarget

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ExpressEventBridge.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ExpressEventRule.Arn

Outputs:
  ExpressApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Express function"
    Value: !Sub "https://${ExpressApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
